### variables
@employeeAccess=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMDAwMSIsImlhdCI6MTc0MDU1Mzg2OCwiZXhwIjoxNzQwNTY0NjY4fQ.4kpaafy7AKXcqpV4O3NL2SoMJ54qsWMzaI3ufI58xtufAIFxamxw7lWRdOrtsATE6kaIBFyOnOYxlLjsyE-vqA
@adminAccess=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc0MDU1MzkxNSwiZXhwIjoxNzQwNTY0NzE1fQ.EIQtLO7xlQCyR6AWOqz4RTqB8m25lskC09GbC_cmTuwy9i7oVSI57vhlIiMQl93qEpdqmX8t63EQUSE5FEV1Pw

#####################################################################################################################

### login (public & all users)
POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "10001",
    "password": "passworD#1"
}

### login for admin
POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "adminPassword"
}


### create new attendance (auth user and employee)
POST http://localhost:8080/api/attendance HTTP/1.1
Authorization: Bearer {{employeeAccess}}
Content-Type: application/json


{
 "date": "06/05/2024",     
  "logIn": "08:30",
  "logOut": "17:30"     
}


#### attendance retrieval by Employee and Date Range (auth user and employee)
GET http://localhost:8080/api/attendance/employee/10001?startDate=2024-06-01&endDate=2024-06-10 HTTP/1.1
Authorization: Bearer {{employeeAccess}}
Content-Type: application/json


#### retrieves attendance records for all employees within a date range (admin only)
GET http://localhost:8080/api/attendance/admin?startDate=2024-06-01&endDate=2024-06-10 HTTP/1.1
Authorization: Bearer {{adminAccess}}
Content-Type: application/json

#### list of start data and end date per week (Auth users)
GET http://localhost:8080/api/attendance/weekly-cutoffs HTTP/1.1
Authorization: Bearer {{employeeAccess}}
Content-Type: application/json

#### calculate weekly worked hours (Auth user)
GET http://localhost:8080/api/attendance/employee/10001/weekly-hours?startDate=2024-08-12&endDate=2024-08-18 HTTP/1.1
Authorization: Bearer {{employeeAccess}}
Content-Type: application/json








