### variables
@employeeAccess=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMDAwMSIsImlhdCI6MTczOTk3MjY4MiwiZXhwIjoxNzM5OTgzNDgyfQ.baRlHtgn3o2In1CLrGWgIL2z2l21e0cC6XXQp7WI-_liJIDTD8ApA22ze5ce9euAkIhjLJXygEPSvTngJkufqw
@adminAccess=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc0MDExNDgyMywiZXhwIjoxNzQwMTI1NjIzfQ.ZcHODLczBshz9xHbR5sq9ke67I_Frq3FjAePL5AM31OpfzyVc-pMHbKpPUQKYFi3rYAqcEtv3j4WuSgbB0vA8w

#####################################################################################################################

### login (public & all users)
POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "10001",
    "password": "passworD#1"
}

### login for admin
POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "adminPassword"
}

### add new employee (admin)
POST http://localhost:8080/api/employees
Authorization: Bearer {{adminAccess}}
Content-Type: application/json

{
"employeeNumber": "10035",
  "lastName": "Alert",
  "firstName": "Amber",
  "birthday": "1980-11-22",
  "address": "19 Global City, Taguig",
  "phoneNumber": "797-009-261",
  "sss": "44-2400689-6",
  "philhealth": "539192926451",
  "tin": "642-454-690-000",
  "pagibig": "810850209333",
  "status": "Regular",
  "position": "Corporate Data Scientist",
  "immediateSupervisor": "Lim, Antonio",
  "basicSalary": 60000,
  "riceSubsidy": 1500,
  "phoneAllowance": 2000,
  "clothingAllowance": 1000,
  "grossSemiMonthlyRate": 30000,
  "hourlyRate": 357.14,
  "user": {
    "id": 36
  }
}

### retrieves all employees with partial details.
### Returns a list of AdminEmployeeDTO objects. (admin)
GET http://localhost:8080/api/employees/admin HTTP/1.1
Authorization: Bearer {{adminAccess}}
Content-Type: application/json


### list all employees in full details (admin)
GET http://localhost:8080/api/employees
Authorization: Bearer {{adminAccess}}
Content-Type: application/json

### fetch employee by id (admin)
GET http://localhost:8080/api/employees/28
Authorization: Bearer {{adminAccess}}
Content-Type: application/json

### fetch employee by employee number (admin)
GET http://localhost:8080/api/employees/employeeNumber/10005
Authorization: Bearer {{adminAccess}}
Content-Type: application/json

### fetch all employees basic info as a list (authenticated)
GET http://localhost:8080/api/employees/basic-info
Authorization: Bearer {{employeeAccess}}
Content-Type: application/json

### fetch auth user's full employee info (current auth user)
GET http://localhost:8080/api/employees/me
Authorization: Bearer {{employeeAccess}}
Content-Type: application/json
