### variables
@employeeAccess=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMDAwMSIsImlhdCI6MTc0MjQ3ODMyNCwiZXhwIjoxNzQyNDg5MTI0fQ.RKGTgSGri7B4oQ6JWNdLpBDcJkNY5ENMspauow4-VE5MY65U1cL4rVVhvdhX8GDDd0B3yNlH3RNVazASOyrDZA
@adminAccess=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc0MjQ4MTYzOCwiZXhwIjoxNzQyNDkyNDM4fQ.TMixACyQ8wG_hsV_QeXcx2nKepg-7bBXwOPXL69C_nyMVetvZ5_o5zwuUsBgI107FUO17qzArKbbkVmajRn6tw
#####################################################################################################################

### login (public & all users)
POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "10001",
    "password": "passworD#1"
}

### login for admin
POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "adminPassword"
}

### add new employee (admin)
POST http://localhost:8080/api/employees
Authorization: Bearer {{adminAccess}}
Content-Type: application/json

{
  "employeeNumber": "10035",
  "lastName": "Alert",
  "firstName": "Amber",
  "birthday": "1980-11-22",
  "address": "19 Global City, Taguig",
  "phoneNumber": "097-009-010",
  "sss": "44-2400689-0",
  "philhealth": "539192926450",
  "tin": "642-454-690-009",
  "pagibig": "810850209332",
  "status": "Regular",
  "position": "Corporate Data Scientist",
  "immediateSupervisor": "Lim, Antonio",
  "basicSalary": 60000,
  "riceSubsidy": 1500,
  "phoneAllowance": 2000,
  "clothingAllowance": 1000,
  "grossSemiMonthlyRate": 30000,
  "hourlyRate": 357.14,
  "user": {
    "id": 36
  }
}

### retrieves all employees with partial details.
### Returns a list of AdminEmployeeDTO objects. (admin)
GET http://localhost:8080/api/employees/admin HTTP/1.1
Authorization: Bearer {{adminAccess}}
Content-Type: application/json


### list all employees in full details (admin)
GET http://localhost:8080/api/employees
Authorization: Bearer {{adminAccess}}
Content-Type: application/json

### fetch employee by id (admin)
GET http://localhost:8080/api/employees/28
Authorization: Bearer {{adminAccess}}
Content-Type: application/json

### fetch employee by employee number (admin)
GET http://localhost:8080/api/employees/employeeNumber/10005
Authorization: Bearer {{adminAccess}}
Content-Type: application/json

### fetch all employees basic info as a list (authenticated)
GET http://localhost:8080/api/employees/basic-info
Authorization: Bearer {{employeeAccess}}
Content-Type: application/json

### fetch auth user's full employee info (current auth user)
GET http://localhost:8080/api/employees/me
Authorization: Bearer {{employeeAccess}}
Content-Type: application/json
