### variables
@access=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMDAwMSIsImlhdCI6MTczNzMwODkyNywiZXhwIjoxNzM3MzE5NzI3fQ.g0sX6LGGYnphosQQGr8Ta-s9txMco_7HsjDMzGt-VEcuN4qyg-i3C87ji1ZgjTXEVtR_baDs1YZ0vUVxUh_NYw

### signup
POST http://localhost:8080/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "username": "10001",
    "password": "passworD#1"
}


### login
POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "10001",
    "password": "passworD#1"
}


### test all
GET http://localhost:8080/api/test/all HTTP/1.1


### test one user
GET http://localhost:8080/api/test/user HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access}}


### test all users
GET http://localhost:8080/api/users/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access}}


### test me
GET http://localhost:8080/api/users/me HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access}}