### variables
@access=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczODkzODkyNSwiZXhwIjoxNzM4OTQ5NzI1fQ.V9Lrr27lLoLZ3cpfRnCe8XGa-5_kRAm-dkdqjo6XYbi6AoyxBk51igAAAGTKXZL4cfMFPpcmQ82iO6rcp_Iw7A


### register new user
POST http://localhost:8080/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "username": "user6",
    "password": "passworD#1"
}


### login
POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "user6",
    "password": "passworD#1"
}


### fetch all users (admin)
GET http://localhost:8080/api/users/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access}}


### test me (auth users)
GET http://localhost:8080/api/users/me HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access}}

### add new employee (admin)
POST http://localhost:8080/api/employees
Content-Type: application/json
Authorization: Bearer {{access}}

{
"employeeNumber": "10007",
  "lastName": "San Jose",
  "firstName": "Brad",
  "birthday": "1996-03-15",
  "address": "99 Strosin Hills, Poblacion, Bislig 5340 Tawi-Tawi",
  "phoneNumber": "797-009-261",
  "sss": "40-2400714-1",
  "philhealth": "239192926939",
  "tin": "672-474-690-000",
  "pagibig": "210850209964",
  "status": "Regular",
  "position": "HR Team Leader",
  "immediateSupervisor": "Villanueva, Andrea Mae",
  "basicSalary": 42975,
  "riceSubsidy": 1500,
  "phoneAllowance": 800,
  "clothingAllowance": 800,
  "grossSemiMonthlyRate": 21488,
  "hourlyRate": 255.80,
  "user": {
    "id": 8
  }
}

### fetch all employees (admin)
GET http://localhost:8080/api/employees
Content-Type: application/json
Authorization: Bearer {{access}}

### fetch employee by id (admin)
GET http://localhost:8080/api/employees/1
Content-Type: application/json
Authorization: Bearer {{access}}

### fetch employee by employee number (auth user)
GET http://localhost:8080/api/employees/employeeNumber/10002
Content-Type: application/json
Authorization: Bearer {{access}}

### fetch all users with selected fields (admin)
GET http://localhost:8080/api/employees/admin
Content-Type: application/json
Authorization: Bearer {{access}}