### variables
@access=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMDAzNSIsImlhdCI6MTczOTg1NDcxNSwiZXhwIjoxNzM5ODY1NTE1fQ.I0rDYRgXTYb4eygG506q-84I1M5HSSGpsM8ovc1j_n2fu7xfBBBpb_kEht8Wkj2wkbwxX7AMFI0bIxym1m5XIA
@adminAccess=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczOTg1NDE4OCwiZXhwIjoxNzM5ODY0OTg4fQ.Z0fu7UTwxqCrKFLrGPZr6lkEOsLvco86YmxccaR_wwOlOtn6NVRbihHXzpz7XWvyKJt63YW2-fA_l9I4sM__AA
####### User and test ############

### register new user (admin only)
POST http://localhost:8080/api/auth/register HTTP/1.1
Authorization: Bearer {{adminAccess}}
Content-Type: application/json

{
    "username": "10035",
    "password": "passworD#1"
}


### login (public & all users)
POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "10035",
    "password": "passworD#1"
}

### login for admin
POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "adminPassword"
}


### fetch all users (admin)
GET http://localhost:8080/api/users/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{adminAccess}}


### test me (auth users)
GET http://localhost:8080/api/users/me HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access}}



########## Employee ###########

### add new employee (admin)
POST http://localhost:8080/api/employees
Content-Type: application/json
Authorization: Bearer {{adminAccess}}

{
"employeeNumber": "10035",
  "lastName": "Alert",
  "firstName": "Amber",
  "birthday": "1980-11-22",
  "address": "19 Global City, Taguig",
  "phoneNumber": "797-009-261",
  "sss": "44-2400689-6",
  "philhealth": "539192926451",
  "tin": "642-454-690-000",
  "pagibig": "810850209333",
  "status": "Regular",
  "position": "Corporate Data Scientist",
  "immediateSupervisor": "Lim, Antonio",
  "basicSalary": 60000,
  "riceSubsidy": 1500,
  "phoneAllowance": 2000,
  "clothingAllowance": 1000,
  "grossSemiMonthlyRate": 30000,
  "hourlyRate": 357.14,
  "user": {
    "id": 36
  }
}

### retrieves all employees with partial details.
### Returns a list of AdminEmployeeDTO objects. (admin)
GET http://localhost:8080/api/employees/admin HTTP/1.1
Authorization: Bearer {{adminAccess}}


### list all employees in full details (admin)
GET http://localhost:8080/api/employees
Content-Type: application/json
Authorization: Bearer {{adminAccess}}

### fetch employee by id (admin)
GET http://localhost:8080/api/employees/28
Content-Type: application/json
Authorization: Bearer {{adminAccess}}

### fetch employee by employee number (admin)
GET http://localhost:8080/api/employees/employeeNumber/10005
Content-Type: application/json
Authorization: Bearer {{adminAccess}}

### fetch all employees basic info as a list (authenticated)
GET http://localhost:8080/api/employees/basic-info
Content-Type: application/json
Authorization: Bearer {{access}}

### fetch auth user's full employee info (current auth user)
GET http://localhost:8080/api/employees/me
Content-Type: application/json
Authorization: Bearer {{access}}


