### variables
@employeeAccess=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMDAwMSIsImlhdCI6MTc0MDU1NDMyNCwiZXhwIjoxNzQwNTY1MTI0fQ.vvDni4OHqavaaIJ1bGcaDNXZMOEEFdXe7qypm6-Iq_zXXWSbxNAyRFTzu-0ChI5jNc0nNXieIeVD4WsU03V7hQ
@adminAccess=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc0MDA3MjUzOSwiZXhwIjoxNzQwMDgzMzM5fQ.6DD23EjvGdcz1M88txzykppXLup1I3NQdPW3VtRMGcdpP5TWAUkPA1oowEJugMYriqP19PaEpPDLnHcaV3OYAw

#####################################################################################################################

### login (public & all users)
POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "10001",
    "password": "passworD#1"
}

### login for admin
POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "adminPassword"
}


#### calculate gross weekly salary (Auth user or Admin)
GET http://localhost:8080/api/salary/gross-weekly-salary?startDate=2024-08-12&endDate=2024-08-18 HTTP/1.1
Authorization: Bearer {{employeeAccess}}
Content-Type: application/json


#### calculate net weekly salary (Auth user or Admin)
GET http://localhost:8080/api/salary/net-weekly-salary?startDate=2024-08-12&endDate=2024-08-18 HTTP/1.1
Authorization: Bearer {{employeeAccess}}
Content-Type: application/json