### variables
@employeeAccess=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMDAzMCIsImlhdCI6MTc0MjUyODY1OSwiZXhwIjoxNzQyNTM5NDU5fQ.CYTCpa7iHjCcYvq6OR0HjPbKQy3e_y21A2ODLUq0cTEEI18cV6SWH8WqLeVeIwPn0dseOYpAuxdlYGZl_FJouA
@adminAccess=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc0MjUyODU0NSwiZXhwIjoxNzQyNTM5MzQ1fQ.zEwFkHjh3qPsM2RUxarQKd3Y_JG_T-pdYJ6r0_jJqy85gAD4H78xp-kxnsBPAQownpphQqch7vPNY12tZf2hoA

#####################################################################################################################

### login (public & all users)
POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "10030",
    "password": "passworD#1"
}

### login for admin
POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "adminPassword"
}


#### calculate gross weekly salary (Auth user or Admin)
GET http://localhost:8080/api/salary/gross-weekly-salary?startDate=2024-08-12&endDate=2024-08-18 HTTP/1.1
Authorization: Bearer {{employeeAccess}}
Content-Type: application/json


#### calculate net weekly salary (Auth user or Admin)
GET http://localhost:8080/api/salary/net-weekly-salary?startDate=2024-08-12&endDate=2024-08-18 HTTP/1.1
Authorization: Bearer {{employeeAccess}}
Content-Type: application/json